### ISSUE TITLE
Refactor all protocol related code to frontend

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1010]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

We've been expecting that all protocol-related logic remains in frontend, including protocol parsing and logical planning. For some reason now datanode also keeps a parser and can also accepts SQL queries. Also frontend delegates SQL parsing to datanode in standalone mode:

https://github.com/GreptimeTeam/greptimedb/blob/de0b8aa0a04af3f7ca0ed69e07d5e89aea0919d7/src/frontend/src/instance.rs#L182

This compromise brings a lot of tech debt and maintenance overhead, for example, introducing a new protocol involves both frontend and datanode. Now it's time to get things right.

### Steps
- [x] remove the SQL handler and MySQL server implementation from datanode #1135 
- [x] move the `tests` mod in Datanode to Frontend. They are largely sql and promql tests.
  - [x] make "instance_test.rs" also ran with distributed instance
- [x] move promql exec to frontend
  - [x] also move "promql_test.rs" to frontend
- [x] check sqlness test cases, some may move to "common"

### Implementation challenges

- Move all protocol parsing stuff from datanode to frontend
    - Datanode instance should not implement `SqlQueryHandler` trait, it should only keep a `GrpcQueryHandler` implementation.
https://github.com/GreptimeTeam/greptimedb/blob/de0b8aa0a04af3f7ca0ed69e07d5e89aea0919d7/src/datanode/src/instance/sql.rs#L234
    - The `sql_handler` field of `datanode::instance::Instance` should be moved to frontend instance. `SqlHandler` also has some field like `table_engine` and `catalog_manager`, which in standalone mode, datanode should share these components to frontend so that frontend can build a `SqlHandler`.
https://github.com/GreptimeTeam/greptimedb/blob/75b8afe04359c90e5631ec3164bf42a787fe7e82/src/datanode/src/instance.rs#L71
    - Move the`PromqlHandler` implementation from datanode to frontend. In standalone mode it's also delegated to datanode.
https://github.com/GreptimeTeam/greptimedb/blob/de0b8aa0a04af3f7ca0ed69e07d5e89aea0919d7/src/frontend/src/instance.rs#L528
- Improve our `GrpcQueryHandler` to accommodate more plans and data types.
After the refactoring, datanode accepts only grpc requests with logical plans encoded as substrait (for inserts, gRPC protocol also has an [`Insert`](https://github.com/GreptimeTeam/greptime-proto/blob/36147379c3fd95a10f1cb8a674af1257b7fb5309/proto/greptime/v1/database.proto#L22) variant). Thus we need to support all the possible logical plans and data types in substrait.
    - Logical plan conversions, especially `LogicalPlan::Extension`.
https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/common/substrait/src/df_logical.rs#L305
    - Data type conversions:
https://github.com/GreptimeTeam/greptimedb/blob/d1730a957729d24186c22adbf570697ec900f0f4/src/common/substrait/src/types.rs#L57

**Comment by evenyag** [comment]
@MichaelScofield I create a task list to track the tasks you mentioned in #1135
