### ISSUE TITLE
External table

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1041]
### What problem does the new feature solve?

When querying or processing(even though we don't support real-time processing right now) time series data, we often have to join it with other data. Some data already exists in other storages, such as file system/Kafka/s3 etc., in CSV, parquet, JSON format, etc.

It would be helpful if we can create external tables based on these external data sources.

### What does the feature do?

For example, a CSV file on the local file system `/var/data/city.csv`:

```csv
Rank , Name , State , 2023 Population , 2020 Census , Annual Change , Density (mi²)
1 , New York City , New York , 8,992,908 , 8,804,190 , 0.7% , 29,938
2 , Los Angeles , California , 3,930,586 , 3,898,747 , 0.27% , 8,382
3 , Chicago , Illinois , 2,761,625 , 2,746,388 , 0.18% , 12,146
......
```

Then we can create a table `city` with it:

```sql
MySQL> CREATE EXTERNAL TABLE city with(location="/var/data/city.csv");
```

And query it by SQL:

```sql
MySQL> select * from city;
```

Rank | Name | State | 2023 Population | 2020 Census | Annual Change | Density (mi²)
-- | -- | -- | -- | -- | -- | --
1 | New York City | New York | 8,992,908 | 8,804,190 | 0.7% | 29,938
2 | Los Angeles | California | 3,930,586 | 3,898,747 | 0.27% | 8,382
3 | Chicago | Illinois | 2,761,625 | 2,746,388 | 0.18% | 12,146

Even join it with time series data:

```sql
select temperatures. value, city.population from temperatures  
     left join city on city.name=temperatures.city
```

### Steps
- [x] RFC #1274 
- [x] The parser #1252 
- [x] The file table engine #1323 
- [x] Schema inference #1331 
- [x] #1372
- [x] #1424
- [x] Support parquet format
  -  [x] Parquet factory #1423 
  -  [x] #1463 
- [x] Add Tests
  -  [x] #1460 
- [ ] Update docs
  - [x] https://github.com/GreptimeTeam/docs/issues/338

**Comment by WenyXu** [comment]
We could split this feature into several sub-tasks:
1. SQL parser
2. Support to importing CSV format
3. Register the external table to catalog
4. Design external table retaining policy (e.g., LRU, Retain, Delete after the session closed)
4. Extranal table retaining manager 

BTW, The external table should be immutable?

**Comment by evenyag** [comment]
> The external table should be immutable?

I think it should be immutable. DataFusion supports reading from external data sources like CSV and Parquet. We could find a way to reuse its ability.

**Comment by WenyXu** [comment]
> > The external table should be immutable?
> 
> I think it should be immutable. DataFusion supports reading from external data sources like CSV and Parquet. We could find a way to reuse its ability.
> 
> > CREATE EXTERNAL TABLE city with(location="/var/data/city.csv");
> 
> Maybe we could provide session level external table. Then maybe we don't need to persist it to the catalog manager.

It seems like we should implement the session first.

**Comment by evenyag** [comment]
We should track the related issues and PRs in this issue. e.g. #1274 and #1323 .

**Comment by killme2008** [comment]
@WenyXu Congrats! Look like we already implemented this feature.
