### ISSUE TITLE
Support to copy the table from cloud storage services

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1081]
### What problem does the new feature solve?

We can leverage OpenDAL to implement that import data from or export data to different cloud storage services.

As the divergence shown in PR #1064, we need to discuss the Copy From syntax further.

The main divergence of the Copy From Syntax is whether we should retrieve the parameters from URI (e.g., `s3://bucket/to/path/filename` ) and separate the connection-related options(e.g., ENDPOINT_URL, ACCOUNT_NAME, ACCOUNT_KEY ) into `CONNECTION` clause. Or just put all options into `WITH` clause.

In the #1064 PR, I proposed a draft.It contains a URI parser. The main roles of the URI parser:
- Distinguish protocol
   - s3, azblob, gcs, obs (corresponding to OpenDAL's backend)
   - fs (starting with `/` or ``)
   - http/https (starting with `http`)
- Extract
  - bucket(s3)
  - container (azblob,gcs,obs)
  - hostname (http/https)
- Split path and filename(if any)

 The #1064 's implementation will look like:
```sql
COPY tab FROM 'https://host/to/path/' WITH (FORMAT='parquet')
COPY tab FROM 's3://bucket/to/path/' WITH (FORMAT='parquet') CONNECTION (ENDPOINT='https:://xxx.com')
```

If we put all options into `WITH` clause
```sql
COPY tab FROM '/to/path/' WITH(FORMAT='parquet', ENDPOINT_TYPE='S3', S3_ENDPOINT='https:://xxx.com', BUCKET='bucket')
```

### #1064 Syntax (Draft) 
```
COPY [<database>.]<table_name>
FROM { '<path>/[<filename>]' }
[ WITH 
 (
   [ FORMAT =  { parquet } ]
   [ ,PATTERN = '<regex_pattern>' ]
 )
]
[ CONNECTION 
 (
   [ ENDPOINT = '<uri>' ]
   [ ,ACCESS_KEY_ID = '<key_id>' ]
   [ ,SECRET_ACCESS_KEY = '<access_key>' ]
   [ ,SESSION_TOKEN = '<token>' ]
   [ ,REGION = '<region>' ]
   [ ,ENABLE_VIRTUAL_HOST_STYLE = '<boolean>']
   ..
 )
]
```

### Core 
- [x] Implement the `Copy From` Parser #1092 
- [x] Implement the `Copy From` SqlHandler #1064 
- [x] Connection clause for COPY TO #1163 
- [x] Add tests for local file system (sqlness) @WenyXu #1198 
- [x] Add more tests for S3 #1163 
- [x] Add Docs https://github.com/GreptimeTeam/docs/issues/234
- [x] Combine `Copy From` and `Copy To` #1197 
- [ ] Implemented in Greptime Cluster as well #1344 

### Chores
- [x] #1137 ( Remaining suggestions in the  #1064 )

### Support other cloud service backends 
- [ ] [Google Cloud Storage](https://cloud.google.com/storage)
- [ ] [Azure Storage Blob](https://azure.microsoft.com/en-us/services/storage/blobs/)
- [ ] [Aliyun Object Storage Service](https://www.aliyun.com/product/oss) (OSS)
- [ ] [Huawei Cloud Object Storage](https://www.huaweicloud.com/intl/en-us/product/obs.html) (OBS)

### Related Issues
- #1038

**Comment by killme2008** [comment]
Hmm. I prefer the `CONNECTION` clause, personally.

The critical point is to make the implementation extendable and elegant. Maybe we should add a `Datasource` abstraction that abstracts all data sources to copy from.

**Comment by evenyag** [comment]
> [ CONNECTION 
>  (
>    [ ENDPOINT = '<uri>' ]
>    [ ,ACCESS_KEY_ID = '<key_id>' ]
>    [ ,SECRET_ACCESS_KEY = '<access_key>' ]
>    [ ,SESSION_TOKEN = '<token>' ]
>    [ ,REGION = '<region>' ]
>    [ ,ENABLE_VIRTUAL_HOST_STYLE = '<boolean>']
>    ..
>  )
> ]

Cloud providers might have different connect configurations:
- S3
  - bucket
  - endpoint
  - region
  - access_key_id
  - secret_access_key
  - security_token
- Azure Storage Blob
  - container
  - endpoint
  - account_name
  - account_key

The syntax for all different data sources is verbose. The parser might only parse required parameters such as `ENDPOINT` and pass remaining pairs to the backend.
```
[ WITH 
 (
   [ FORMAT =  { parquet } ]
   option [, ...]
 )
]
[
CONNECTION
(
[ ENDPOINT = '<uri>' ],
option [, ...]
)
]
```

What's more, the parser shouldn't be aware of the content inside `ENDPOINT` or parsing the URI. However, I'm not sure whether we should add another option to specify the endpoint type.

**Comment by fengjiachun** [comment]
Currently, only the distributed mode‘s task is left. I think this issue can be completed and the remaining work will be tracked in #1344.
