### ISSUE TITLE
Fault Tolerance for Regions in distribute mode

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1126]
### What problem does the new feature solve?

Fault tolerance for regions is a critical feature for high availability(HA) in distribute mode, which we currently lack of.

This issue tracks the sub-tasks that gradually achieve region HA in distribute mode.

### What does the feature do?

Sub-tasks:

- [x] [RFC](https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/rfcs/2023-03-08-region-fault-tolerance.md): https://github.com/GreptimeTeam/greptimedb/pull/1139 : [rendered](https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/rfcs/2023-03-08-region-fault-tolerance.md)

WAL:
- [x] ~~Remote WAL: https://github.com/GreptimeTeam/greptimedb/issues/626~~ (Not planned here. Made some compromise on strict data reliability.)

In Datanode:
- [x] open/close region (table) upon receiving heartbeat instructions from Meta 
  - [x] heartbeat response handler #1547
  - [x] open region #1567
  - [x] close region #1569 

- [ ] ~~Local global WAL  for testing purpose.~~

In Meta:
- [x] failure detector #1200 
- [x] failover executor with distributed procedure https://github.com/GreptimeTeam/greptimedb/pull/1558

In Frontend:
- [x] heartbeat mechanism to deal with region failover #1189
  - [x] #1627
  - [x] #1633
  - [x] #1658
- [ ] properly handles read/write to accommodate with region failover
  - [x] #1673

Testing:
- [ ] with [madsim](https://github.com/madsim-rs/madsim)
- [ ] with [argo workflow](https://github.com/argoproj/argo-workflows/)

**Comment by killme2008** [comment]
Can we write an RFC for this feature? It's really important.

**Comment by MichaelScofield** [comment]
will do

**Comment by MichaelScofield** [comment]
testing (chaos mesh, argo workflow, operator etc) will be tracked in new issues
