### ISSUE TITLE
Tracking Issue for `StorageEngine::open_region()`

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#114]
This is a tracking issue for implementing the `StorageEngine::open_region()` method.

## Tasks
- [x] Adds `RegionImpl::open()` to open and recover a region
    - [x] Code skeleton @evenyag  #120 
    - [x] `RegionImpl::recover_from_manifest()` Loads metadata from manifest and construct `Version` @killme2008 #127 
        - [x] `RegionManifest::load()` should also load `VersionEdit`
        - [x] `RegionManifest::update()` should persist metadata of `Version`(`flushed_sequence`)
    - [x] Replay data from wal
        - [x] Reads logstore and decode wal entry, implement `Wal::decode_entry()` @fengjiachun #123 
        - [x] `RegionWriter::replay()` replay batch into memtable, maintains `Version` @evenyag #135 
    - ~Adds an option to `OpenOptions` to create region if it is absent (optional feature)~
- ~Manifest uses `prev_version` to construct the metadata change list (optional feature)~ @killme2008 
- [x] Remove id from `Namespace` of logstore #120 
    - [x] Also remove `region_id` from `Wal::new()` #120 
- [x] Concurrent control of opening/creating region #120 
    - Related issue is #113 
    - Maybe we should introduce state (enum) for region
- [x] Implements `LogStore::read()` @v0y4g3r  #124 
- [x] Add tests for open @evenyag #135 

## Related Tasks
- We may also need to add a `TableEngine::open_table()` method to open all regions of this table #117 
- Support dynamic polymorphism for `TableEngine` #119
