### ISSUE TITLE
Collect and use statistics of table data

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1431]
### What problem does the new feature solve?

Statistics is an important part of helping improve the system's overall performance. With statistics, the optimizer can analyze the size and distribution of tables, estimate cardinalities, and choose the most efficient execution plan. And it provides valuable insights into the data stored in tables, allowing system manager or user to make informed decisions about how to manage, query, and analyze the data.

There are two existing statistics, one counts the total data size during insertion, and one is generated from parquet file format when flushing SSTs. We can consider adding more useful counters, and then expose them properly.

Several possible consumers of statistics might be: (a) the query optimizer and executor, (b) the system scheduler and manager, (c) users who are curious about those statistics and (d) the indexer. Thus we need to design a proper way to organize and provide those statistics.

### What does the feature do?

- [ ] Be able to access statistics from parquet format #1429
- [ ] Find out how to organize our layered statistics
- [ ] Use statistics to optimize `COUNT (*)`
- [ ] Collect statistic on write #1231
