### ISSUE TITLE
Purge expired state files and metadata once a procedure is finished

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1509]
### What problem does the new feature solve?

The procedure framework stores procedures' states in the procedure store. e.g.
```
/procedure/{procedure-id}/0000000000.step
/procedure/{procedure-id}/0000000001.commit
```

Now we never clean the procedure store. However, once the procedure is finished (committed or rollbacked), we could remove these state files. We could add a TTL to retain the files for some time so we could still query the procedure's state.

### What does the feature do?

We need to remove the state files of a procedure when the procedure is finished and the files have outlived a specific TTL.

Note that we support subprocedures, so we also need to ensure the root procedure is finished before we remove the state files.

#### ProcedureStore
First, we need to implement a new method `delete_procedure` to remove all state files for a specific `procedure id`.
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/store.rs#L48-L50

We can use the state store to scan all files under the given path and removes them.
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/store/state_store.rs#L40-L48

Be careful that we need to remove all `.step` files first and then remove the `.commit` or `.rollback` files. So we need to call `delete()` twice.

#### Pruge ProcedureManager Periodically
Then we could implement the purge feature in the procedure manager. We need to keep track of finished procedures in the procedure manager. Once a root procedure is finished, the runner pushes the procedures' ids in the tree and the finished time to the procedure manager
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/local/runner.rs#L151-L154

The procedure manager starts a repeated task in the background to purge the files of the procedure periodically.
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/runtime/src/repeated_task.rs#L59-L60

The purge task might also need to remove the meta in memory.
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/local.rs#L126

#### Restart
When the procedure manager restarts, we could also find out which procedure is finished and purge all expired files. One approach is refactoring `load_messages` to also return finished procedures.
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/store.rs#L123C1-L124

Then we remove files in `recover`
https://github.com/GreptimeTeam/greptimedb/blob/2818f466d3fc0cb1abf78c4248b87b7353e5d9d2/src/common/procedure/src/local.rs#L383

#### Steps
We could further divide this issue into small tasks:
- [x] Implement `remove_procedure` in the `ProcedureStore` #1543
- [x] Purge expired state files after the procedure finishes #1543
- [x] Purge expired state files on procedure manager restart #1543
- [x] Use a `RepeatedTask` to invoke `remove_outdated_meta()`, instead of calling it when submitting or querying procedures #1578

**Comment by NiwakaDev** [comment]
I'd like to work on this issue!!

**Comment by evenyag** [comment]
Hi, @NiwakaDev , I plan to change the purge strategy to remove states directly after the procedure is committed. I'd open a PR to implement `remove_procedure` and this strategy first. Let's stay tuned.

**Comment by NiwakaDev** [comment]
Hi, @evenyag 

>I plan to change the purge strategy to remove states directly after the procedure is committed

I see.

>I'd open a PR to implement remove_procedure and this strategy first. Let's stay tuned.

Ok. You mean that I need to implement step2(Purge expired state files and metadata in memory periodically) and step3(Purge expired state files on procedure manager restart), not step1?

**Comment by evenyag** [comment]
@NiwakaDev I have finished steps 1 ~ 3 in #1543 . I plan to refactor the `RepeatedTask` and after that, you could go to step 4 directly.

**Comment by NiwakaDev** [comment]
>I plan to refactor the RepeatedTask and after that, you could go to step 4 directly.(I update the steps above)

Ok.

**Comment by NiwakaDev** [comment]
H, @evenyag

>I plan to refactor the RepeatedTask and after that, you could go to step 4 directly.(I update the steps above)

It seems like the steps above have been updated. Have you finished refactoring the RepeatedTask?

**Comment by evenyag** [comment]
> It seems like the steps above have been updated. Have you finished refactoring the RepeatedTask?

https://github.com/GreptimeTeam/greptimedb/pull/1545 is merged, you could work on this now. @NiwakaDev
