### ISSUE TITLE
UDF & UDAF functions

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1536]
### What type of enhancement is this?

API improvement

## Datafusion built-in functions
Since GreptimeDB's query engine is built based on Apache Arrow DataFusion, GreptimeDB inherits all built-in functions in DataFusion. These functions include:

Aggregate functions: such as COUNT(), SUM(), MIN(), MAX(), etc. For a detailed list, please refer to [Aggregate Functions](https://arrow.apache.org/datafusion/user-guide/sql/aggregate_functions.html)

Scalar functions: such as ABS(), COS(), FLOOR(), etc. For a detailed list, please refer to [Scalar Functions](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html)

## Custom functions
We already implemented some custom functions in 

https://github.com/GreptimeTeam/greptimedb/blob/c48067f88d31c28021fcd5560eb8c46d3e2b3940/src/common/function/src/scalars/function_registry.rs#L73-L75

But still missing a lot of useful functions such as Date Functions, Date Format functions, Time-Series Utility Functions and other Utility functions etc.

So let's create a tracking issue for them:

* [ ] Date and Time Functions, [duckdb](https://duckdb.org/docs/sql/functions/date),[questdb](https://questdb.io/docs/reference/function/date-time/) and [influxdb](https://docs.influxdata.com/influxdb/cloud-serverless/reference/sql/functions/time-and-date/) for example.
* [ ] Date Format Funcitons, [duckdb](https://duckdb.org/docs/sql/functions/dateformat)
* [ ] Utility Functions for admin etc. [duckdb](https://duckdb.org/docs/sql/functions/utility)
* [ ] Time-Series Utility Functions, such as `gafill`, percentile and histogram related functions,  `locf` etc.
* [ ] Predicator
* [ ] Abnormal detector

## Ref

* [how-to-write-aggregate-function](https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/how-to/how-to-write-aggregate-function.md)

**Comment by NiwakaDev** [comment]
@killme2008 

> Date and Time Functions, duckdb,questdb and influxdb for example.

I'd like to implement some of the features for example:
1. [greatest(date, date)](https://duckdb.org/docs/sql/functions/date)
2. [to_timezone](https://questdb.io/docs/reference/function/date-time/#to_timezone)
3. [current_schema()](https://duckdb.org/docs/sql/functions/date)

By the way, does `greptimedb` have plans to support something statistical in sql, like so:
* inner_product(column1, column2): UDAF
* covariance(column1, column2): UDAF

**Comment by killme2008** [comment]
@NiwakaDev That would be cool,thanks a lot.

`to_timezone` looks like it's implemented in #2029 

> By the way, does greptimedb have plans to support something statistical in sql, like so:

Of course, we want to support these functions.

**Comment by tisonkun** [comment]
@killme2008 May you give a revise what the remaining UDF/UDAF listed above is still to-be-implemented? They should be good first issue to follow.

**Comment by tisonkun** [comment]
Closed as stale.

We can create a new issue with concrete list of UDF/UDAF to support so that certain contributions can be made.

Vague names of functions are hard to be understood and picked up.
