### ISSUE TITLE
Tracking issue for implementing mito as a region engine

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1869]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

For historical reasons, both frontend and table engines (run in datanode) are aware of multiple regions in a table. That makes implementing a distributed table with multi-regions support complicated. We need to deal table and its regions on both frontend and datanode. We also need to implement procedures for the mito engine to ensure the eventual consistency of altering a table.

We decide to turn the table engine into a region engine, which only has knowledge of regions.
- The `TableEngine` trait becomes `RegionEngine` and only deals with regions.
- The datanode acts like a `RegionServer`. It manages regions assigned to the node and provides region-level access.
- The frontend provides table-level access. It partitions requests and routes them to regions on datanodes.
- We can combine the `StorageEngine` with the `mito` table engine.
- Since we already store metadata of the table in `metasrv`, there is no need to persist them again to the table manifest. We can remove the table manifest.
- Altering multiple regions is tracked by the procedure inside `metasrv`. We don't need procedures for the mito engine.

### Steps
We are going to create a new fork of `mito` crate (maybe `mito2`).
- [x] A new crate `mito2` #1875
- [x] RFC https://github.com/GreptimeTeam/greptimedb/pull/1899
- [x] Use `TableInfo` to replace `RegionMetadata` (We might still reuse the `RegionSchema`)
- [x] Implement `MitoRegion` or `MitoRegionInfo` to hold metadata #1989 
- [x] Create region #1999 
- [x] Open region #2052
- [x] Close region #2052 
- [x] Wal #2103
- [x] Write region #2135
  - [x] #2250
- [x] Delete rows #2275
- [x] New memtable #2208
- [x] Scan region
  - [x] New Batch #2174
  - [x] Merge reader #2210
  - [x] Skeleton #2230
- [x] Flush region
  - [x] Framework #2262
  - [x] Write buffer manager #2309
  - [x] Write stall #2322
- [x] Alter region
  - [x] Compat reader #2326
  - [x] Skeleton #2343
- [x] Compact region
  - [x] Skeleton #2317
  - [x] Scheduler #2413
- [x] region options #2436
- [x] Combine `RegionManifest` and `StorageManifest` #1984 
- [x] Remove the `Region` trait and forward requests to the engine directly
- [x] Refactor `file` table engine if necessary #2365 
- [x] Remove `TableEngineProcedure` trait
- [x] Remove procedure implementations in `mito` and `file` engine
- [x] Replace `mito` with `mito2` (rename `mito2` to `mito`)
- [x] Rename `TableEngine` to `RegionEngine`
- [x] Remove the old `StorageEngine` and related traits

#### Other Enhancements
There are also some other enhancements we could achieve during refactoring mito. They may not be strictly related to this issue's topic.
- [x] Remove dependency of log `sequence` from `RegionMetaAction::Change`
- [x] Decouple `LogStore` index and engine sequence (switch to sequence per key mode)
- [x] Remove `Option` from time range in `FileMeta`
- [x] Implement a new `RegionWriter` that supports batching (group commit)
- [x] ~~Add column family support?~~ We plan to remove column family

**Comment by killme2008** [comment]
Looks like we can close this issue 👍
