### ISSUE TITLE
tracking issue for refactoring the `Table` trait and related structures

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2065]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

With table engine in datanode being replaced by region engine in https://github.com/GreptimeTeam/greptimedb/issues/1869, we should also reconsider the `Table` abstraction. Generally speaking, the datanode (or region server) will no longer be aware of table -- it only sees and handles regions. And consequently, all the data access kind API (read, write, delete etc.) should be removed from `Table`. This makes the `Table` trait only in response of metadata, like retrieving table info or table schema.

This change will be shipped in the following parts:
- [x] RFC document #2106
- [x] Add route info into `TableInfo` #2000
- [x] Implement the two tables under the information schema in the flavor of `TableFactory`
- [x] Remove `PartitionExec`, which is used to serve `DistTable`'s `scan()` method
- [x] Adapt Region Server's region operation requests
- [x] Adapt DataFusion's table source to the new datanode (region server)
- [x] Refactor those `*Adaptor`s and `*Adapter`s https://github.com/GreptimeTeam/greptimedb/issues/1665
- [x] Replace the old `Table` trait with the new `Table` struct #2270

**Comment by waynexia** [comment]
Close as completed

**Comment by tisonkun** [comment]
@waynexia @zhongzc But we still have the `Table` trait and `Arc<dyn Table>` in many places. Shall we continue on this direction?

**Comment by tisonkun** [comment]
I'm trying to drop the Table trait ...
