### ISSUE TITLE
2022/05 todo

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#22]
* [x] sql planner
* [x] http server for datanode
* [x] refactor errors
* [x] metric/log/tracing
* [x] config #156 
* [x] impl more datatypes
* [x] storage layer design
* [x] storage poc #107 
* [x] udf poc
