### ISSUE TITLE
[tracking] failed sqlness cases

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2367]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

- [x] tests/cases/distributed/explain/join_10_tables.sql @waynexia 
- [x] tests/cases/distributed/explain/multi_partitions.sql @waynexia 
- [x] tests/cases/distributed/explain/order_by.sql @waynexia 
- [x] tests/cases/distributed/explain/single_partition.sql @waynexia 
- [x] tests/cases/distributed/explain/subqueries.sql @waynexia 
- [x] tests/cases/distributed/optimizer/filter_push_down.sql @waynexia 
- [x] tests/cases/distributed/optimizer/order_by.sql @waynexia 
- [x] tests/cases/distributed/tql-explain-analyze/analyze.sql @waynexia 
- [x] tests/cases/distributed/tql-explain-analyze/explain.sql @waynexia 
- [x] tests/cases/standalone/common/system/information_schema.sql @waynexia 
- [x] tests/cases/standalone/common/aggregate/distinct.sql
- [x] tests/cases/standalone/common/aggregate/distinct_order_by.sql
- [x] tests/cases/standalone/common/aggregate/sum.sql
- [x] tests/cases/standalone/common/alter/add_col.sql @evenyag 
- [x] tests/cases/standalone/common/alter/add_col_chain.sql @evenyag 
- [x] tests/cases/standalone/common/alter/add_col_default.sql @evenyag 
- [x] tests/cases/standalone/common/alter/alter_table.sql @evenyag 
- [x] tests/cases/standalone/common/alter/alter_table_first_after.sql @evenyag 
- [x] tests/cases/standalone/common/alter/drop_col.sql @evenyag 
- [x] tests/cases/standalone/common/alter/drop_col_not_null.sql @evenyag 
- [x] tests/cases/standalone/common/alter/drop_col_not_null_next.sql @evenyag 
- [x] tests/cases/standalone/common/alter/rename_table.sql @evenyag 
- [x] tests/cases/standalone/common/basic.sql @zhongzc 
- [x] tests/cases/standalone/common/catalog/schema.sql
- [x] tests/cases/standalone/common/copy/copy_from_fs_csv.sql
- [x] tests/cases/standalone/common/copy/copy_from_fs_json.sql
- [x] tests/cases/standalone/common/copy/copy_from_fs_parquet.sql
- [x] tests/cases/standalone/common/copy/copy_to_fs.sql
- [x] tests/cases/standalone/common/create/upper_case_table_name.sql
- [x] tests/cases/standalone/common/cte/cte.sql
- [x] tests/cases/standalone/common/cte/cte_in_cte.sql
- [x] tests/cases/standalone/common/delete/delete.sql
- [x] tests/cases/standalone/common/insert/big_insert.sql  @killme2008 
- [x] tests/cases/standalone/common/insert/insert.sql @killme2008 
- [x] tests/cases/standalone/common/insert/insert_default.sql @killme2008 
- [x] tests/cases/standalone/common/insert/insert_invalid.sql @killme2008 
- [x] tests/cases/standalone/common/insert/insert_select.sql @killme2008 
- [x] tests/cases/standalone/common/order/limit.sql @killme2008 
- [x] tests/cases/standalone/common/order/limit_union.sql @killme2008 
- [x] tests/cases/standalone/common/order/nulls_first.sql @killme2008 
- [x] tests/cases/standalone/common/order/order_by.sql @waynexia 
- [x] tests/cases/standalone/common/order/order_by_exceptions.sql @killme2008 
- [x] tests/cases/standalone/common/order/order_variable_size_payload.sql
- [x] tests/cases/standalone/common/types/float/nan_aggregate.sql @killme2008 
- [ ] tests/cases/standalone/common/types/interval/interval.sql @killme2008 
- [x] tests/cases/standalone/common/types/string/bigstring.sql @killme2008 
- [x] tests/cases/standalone/common/types/string/scan_big_varchar.sql @killme2008 
- [x] tests/cases/standalone/common/types/string/unicode.sql @killme2008 
- [x] tests/cases/standalone/common/types/timestamp/timestamp.sql @killme2008 

@MichaelScofield :
- [x] tests/cases/standalone/common/select/dummy.sql
- [x] tests/cases/standalone/common/select/like.sql
- [ ] tests/cases/standalone/common/select/range_select.sql
- [x] tests/cases/standalone/common/tql/aggr_over_time.sql
- [x] tests/cases/standalone/common/tql/basic.sql
- [x] tests/cases/standalone/common/tql/binary_operator.sql
- [x] tests/cases/standalone/common/tql/join.sql
- [x] tests/cases/standalone/common/tql/operator.sql

**Comment by WenyXu** [comment]
**Updates**

*Remain*
- [ ] common/select/range_select
- [ ] common/types/interval/interval

*Broken*
- [ ] common/alter/rename_table
- [ ] optimizer/filter_push_down
- [ ] show/show_create

**Comment by waynexia** [comment]
This is what I get from 542e863ecc3a0503a85d76729dccc2609f565b8b:
- [ ] distributed/optimizer/filter_push_down.sql
- [ ] distributed/optimizer/order_by.sql
- [ ] distributed/show/show_create.sql
- [ ] standalone/common/alter/alter_table_first_after.sql
- [ ] standalone/common/alter/rename_table.sql
- [ ] standalone/common/cte/cte_in_cte.sql
- [ ] standalone/common/select/range_select.sql
- [ ] standalone/common/tql/aggr_over_time.sql
- [ ] standalone/common/types/interval/interval.sql
- [ ] standalone/common/types/timestamp/timestamp.sql
- [ ] standalone/optimizer/filter_push_down.sql
- [ ] standalone/show/show_create.sql

**Comment by killme2008** [comment]
The latest result in develop branch:

```
    "standalone/common/alter/rename_table",
    "standalone/common/select/range_select",
    "standalone/common/types/interval/interval",
    "standalone/optimizer/filter_push_down",
    "standalone/show/show_create",

    "distributed/common/select/range_select",
    "distributed/common/types/interval/interval",
    "distributed/optimizer/order_by",
    "distributed/show/show_create",
```

**Comment by waynexia** [comment]
I'm looking at `show/show_create`
