### ISSUE TITLE
[Tracking] check and fix the ignored tests

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2401]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

* [ ] `stddev_by_label` in tests-integration/src/tests/promql_test.rs
* [x] `test_distributed_exec` in tests-integration/src/opentsdb.rs
* [x] `test_alter_table` in tests-integration/src/tests/instance_test.rs
* [x] `test_repl` in src/cmd/tests/cli.rs
* [x] `test_meter_insert_request` in src/frontend/src/table.rs
* [x] `test_insert_find_compile_script` in src/script/src/manager.rs
* [x] `transform_simple_projection_filter` in src/query/src/dist_plan/analyzer.rs
* [x] `test_query_prepared` in src/servers/tests/mysql/mysql_server_test.rs
* [x] `binary_op_literal_literal` in src/promql/src/planner.rs
* [x] `bool_with_additional_arithmetic` in src/promql/src/planner.rs
