### ISSUE TITLE
Enable `LeaderCachedKvStore` for meta server

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2604]
### What type of enhancement is this?

Performance, Refactor, Tech debt reduction

### What does the enhancement do?

The meta server needs a cheap way to ensure the Datanode servers hold the correct `Writable Region` and `Read-only Region`. Due to all metadata mutation should be executed via meta server leader in distribution mode, we can utilize this character to cache all metadata in the meta server's memory.

### Steps
**Reclaim Mutation permissions**
- [ ] Introduce the `ReadonlyKvBackend` for Frontend and Datanode.
- [ ] #2601 

**Enable `LeaderCachedKvStore`**
- [ ] Add `initializing` stage for caching key-value
- [ ] Reject requests during the `initializing` stage
