### ISSUE TITLE
Tracking issue for Region Migration

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2700]
### What problem does the new feature solve?

As mentioned in #1622, Region Migration moves the region between Datanodes.

#### RFC
- [x] RFC document #2703 

#### Meat Server

 - [x] #3014
 - [x] HTTP API
   - [x] #3015
   - [x] #3032
 - [x] Upgrade the Follower Region to the Leader Role.
   - [x] #2704
   - [x] #2718
 - [x] Set the `downgraded` flag before deactivating a Region.
   - [x] #2670
 - [x] Remove the Inactive Region Manager.
   - [x] #2715
   - [x] #2729
 - [x] Enable new Region Lease Keeper.
   - [x] #2645
 - [x] Migration Procedure.
   - [x] #2743
   - [x] #2752
   - [x] #2756 
   - [x] #2757
   - [x] #2771
   - [x] #2792 
   - [x] #2811
   - [x] #2812
   - [x] #2829

#### Datanode
 - [x] Report Region Role. https://github.com/GreptimeTeam/greptimedb/pull/2640
 - [x] #2855
 - [x] #2977
 - [x] #2955
 - [x] #2939
 - [x] #3013

#### Tests
 - [x] #2857
 - [x] #2895
 - [x] #3078
#### Others
 - [x] #3066
 - [x] #3086
 - [x] #3061
 - [x] #3077
 - [x] #3094
