### ISSUE TITLE
Tracking issue for introducing inverted index

### ISSUE THREAD

**Issue by zhongzc** [GreptimeTeam/greptimedb#2705]
### What type of enhancement is this?

Performance

### What does the enhancement do?

> In the current system setup, in the Mito Engine, the first column of Primary Keys has a Min-Max index, which significantly optimizes the outcome. However, there are limitations when it comes to other columns, primarily tags. This RFC suggests the implementation of an inverted index to provide enhanced filtering benefits to bridge these limitations and improve overall system performance.

This issue is used to track the relevant implementation tasks of [RFC](https://github.com/GreptimeTeam/greptimedb/blob/main/docs/rfcs/2023-11-03-inverted-index.md):
* [x] Read and write files in Puffin format
  * https://github.com/GreptimeTeam/greptimedb/pull/2725
  * https://github.com/GreptimeTeam/greptimedb/pull/2741
  * https://github.com/GreptimeTeam/greptimedb/pull/2751
  * https://github.com/GreptimeTeam/greptimedb/pull/2776
* [x] Read and write Blob in `greptime-inverted-index-v1` format within Puffin file
  * https://github.com/GreptimeTeam/greptimedb/pull/2803
  * https://github.com/GreptimeTeam/greptimedb/pull/2900
* [x] Implementation of index searcher
  * https://github.com/GreptimeTeam/greptimedb/pull/2851
  * https://github.com/GreptimeTeam/greptimedb/pull/2862
  * https://github.com/GreptimeTeam/greptimedb/pull/2868
* [x] Implementation of index creator
  * https://github.com/GreptimeTeam/greptimedb/pull/2942
  * https://github.com/GreptimeTeam/greptimedb/pull/2950
  * https://github.com/GreptimeTeam/greptimedb/pull/2960
* [x] Integration with the existing Parquet SST reader
  * https://github.com/GreptimeTeam/greptimedb/pull/3034
  * https://github.com/GreptimeTeam/greptimedb/pull/3068
  * https://github.com/GreptimeTeam/greptimedb/pull/3088
  * https://github.com/GreptimeTeam/greptimedb/pull/3130
* [x] Integration with the existing Parquet SST writer
  * https://github.com/GreptimeTeam/greptimedb/pull/3107
  * https://github.com/GreptimeTeam/greptimedb/pull/3144
  * https://github.com/GreptimeTeam/greptimedb/pull/3158
* [ ] Add variables to control apply on query

**Comment by tisonkun** [comment]
@zhongzc Is there any further remaining task here?

**Comment by killme2008** [comment]
I think we can close this issue. cc @zhongzc
