### ISSUE TITLE
Tracking issue for altering table schema

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#275]
Currently we have not yet fully implemented the procedure of altering the schema of a table, which is necessary to support things like SQL DDL, opentsdb protocol.

This is a tracking issue for implementing a MVP (minimal viable product) for altering table schema, which allows:
- add a new column to the table
- remove an existing value column (not the column in primary key index or time index) from the table

Here is a list of tasks need to be done
- [x] #277 @v0y4g3r 
  - Also need to maintain state of altering (maybe stores the new schema in the state)
- [x] #278 @evenyag 
- [x] #281 @killme2008 
  - [x] #282 @killme2008 
- [x] #284 @evenyag 
- [x] Remove `column_null_mask` in `MutationExtra` @evenyag  #314 
- [x] #285 @evenyag 
- [ ] ~#286~
  - retries unfinished schema altering, maybe done in opening, writing or before altering the table
- [x] Error handling for altering region
- [x] #279 @killme2008 
- [x] #283 @killme2008 
  -  since the datanode takes care of these jobs
- [x] Tests
  - [x] Test the manifest has metadata after last WAL entry @killme2008 
  - [x] Implement `MockRegion::alter()` #287 

## Issues
- [x] #364

**Comment by evenyag** [comment]
I will close this issue as the error handling part #286 is related to the procedure framework.
