### ISSUE TITLE
Tracking issue for the memtable improvement

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2804]
### What type of enhancement is this?

Performance

### What does the enhancement do?

The default memtable [implementation](https://github.com/GreptimeTeam/greptimedb/blob/102e43aace8108012f94781e567caa57f329b810/src/mito2/src/memtable/time_series.rs#L87) has the following areas for improvement:
- The active buffer doesn't have capacity limit, we might freeze it once its size reaches a threshold
- [`compact()`](https://github.com/GreptimeTeam/greptimedb/blob/102e43aace8108012f94781e567caa57f329b810/src/mito2/src/memtable/time_series.rs#L564) and [`to_batch()`](https://github.com/GreptimeTeam/greptimedb/blob/102e43aace8108012f94781e567caa57f329b810/src/mito2/src/memtable/time_series.rs#L669) is costly
  - Most time series data has monotonically increasing timestamps so we can avoid sorting if data is already sorted
- At each query, we need to scan each `Series` to see whether it matches the filter
  - We can use prefix scan if the filter matches a prefix of the primary key
  - In-memory index in the memtable?
- Dropping lots of [`Series`](https://github.com/GreptimeTeam/greptimedb/blob/102e43aace8108012f94781e567caa57f329b810/src/mito2/src/memtable/time_series.rs#L529) is costly, we should explore the possibility of reusing `Series`
- The basic overhead of `ValueBuilder` is relative high when each time-series has only a few data points.

### Implementation challenges

We might implement some benchmarks and optimize the memtable based on test results.

### Implementation history
- [x] Support building a vector without resetting the builder https://github.com/GreptimeTeam/greptimedb/pull/2915
- [x] Per table setting https://github.com/GreptimeTeam/greptimedb/issues/3183
- [x] Implementation
  - [x] basic structs https://github.com/GreptimeTeam/greptimedb/pull/3326
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3329
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3334
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3343
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3346
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3348
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3357
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3361
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3371
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3373
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3374
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3375
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3377
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3378
- [ ] Test and Optimize
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3386
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3393
  - [x] https://github.com/GreptimeTeam/greptimedb/pull/3380
  - [x] memtable read metrics https://github.com/GreptimeTeam/greptimedb/pull/3397
  - [x] reduce pruning cost
    - [x] https://github.com/GreptimeTeam/greptimedb/pull/3415
    - [ ] `last_yield_pk_index` doesn't help to skip already pruned keys
  - [x] reduce cost of finding pk index
    - [x] Replace shard level maps with a partition level map https://github.com/GreptimeTeam/greptimedb/pull/3400
    - [x] Maybe change the encoding of the key in the map https://github.com/GreptimeTeam/greptimedb/pull/3410
 - [x] Benchmarks https://github.com/GreptimeTeam/greptimedb/pull/3491
 - [ ] Optimize scan performance https://github.com/GreptimeTeam/greptimedb/issues/3467
  - [ ] projection push down
  - [x] Reduce read-write lock contention
    - [x] https://github.com/GreptimeTeam/greptimedb/pull/3406
  - [x] Enable it by default https://github.com/GreptimeTeam/greptimedb/pull/3430
  - [x] Rename the memtable https://github.com/GreptimeTeam/greptimedb/pull/3547
  - [ ] `fork_dictionary_bytes` should be global config

#### Non-Blocking
- [ ] more query tests
- [ ] Better freeze strategy

**Comment by killme2008** [comment]
What's the progress of this issue? Could we convert it to a tracking issue and split tasks? @evenyag @v0y4g3r

**Comment by evenyag** [comment]
We need some experiments and benchmarks to examine some ideas.

**Comment by evenyag** [comment]
I'm going to close this issue as the performance is tracked in https://github.com/GreptimeTeam/greptimedb/issues/3467
