### ISSUE TITLE
Support parallel scan in mito engine

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2806]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Currently, the Mito engine only supports single-threaded scanning. We can consider using parallel scanning to improve speed when dealing with larger amounts of data.

### Implementation challenges

There are several approaches to parallel scanning:
- Parallel scanning of each file: If there is only one file to scan, parallelization is not possible.
- Parallel scanning of row groups: It is important to note that, in order to ensure the final result is sorted, it is necessary to scan the row groups used by the MergeReader. Implementing this approach can be more complex.

We also need to figure out a way to control the parallelism of the query so spawning a task for each file might not be the best solution (We might need some experiments).

### Steps
- [x] Scan files in parallel https://github.com/GreptimeTeam/greptimedb/pull/2852
- [x] Scan row groups in parallel if the table is append only
  - [x] Build multiple ranges to scan https://github.com/GreptimeTeam/greptimedb/pull/3841
  - [x] Scan multiple ranges https://github.com/GreptimeTeam/greptimedb/pull/3992/
- [x] Scan row groups in parallel for non append only table https://github.com/GreptimeTeam/greptimedb/pull/4060
- [x] Fix the pruning issue for columns with the same name but different column ids https://github.com/GreptimeTeam/greptimedb/pull/3802
- [x] https://github.com/GreptimeTeam/greptimedb/issues/3886

**Comment by evenyag** [comment]
I'm going to reopen this issue as file-level parallelism is not enough if the number of parquet files is less than the parallelism. We still need to implement a more fine-grained parallel scan strategy, such as row group level parallel scan. However, parallel scanning row groups might not be able to maintain a sorted order of the SST file. As a result, we can implement this parallel strategy in append only tables that use `UnorderedScan`.

I did some experiments on this [branch](https://github.com/evenyag/greptimedb/blob/poc/bench-parallel/). I also found that we must support multiple output partitioning to maximize computations.
