### ISSUE TITLE
Tracking issue for the procedure framework

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#286]
This is the tracking issue for the procedure framework.

# Steps
- [x] RFC #836 
- [x] PoC: [procedure-api](https://github.com/evenyag/greptimedb/tree/poc/procedure-api)
- [ ] Standalone procedure
  - [x] Procedure API #904 
  - [x] ProcedureStore #927 
  - [x] Framework for local ProcedureManager #946
  - [x] Procedure execution #953 
  - [x] Recover procedures from ProcedureStore #981 
  - [x] Provide a way to watch a procedure #1043
  - [x] Add an error variant RetryLater for recoverable failure. (The default variant External always aborts the procedure.) #1058
  - [x] Max retry times #1095 
  - [x] Provide a way to get the execution error of a procedure #1062 
  - [x] Remove metadata of procedure from memory after specific TTL #1509 
    - [x] Remove metadata when root procedure is done #1543
  - [ ] Cancellation and shutdown #1721
- [x] Procedure for creating a standalone table
  - [x] Refactor CreateTableRequest to make it more convenient to serialize/deserialize #1018 
  - [x] Implement procedure to create table on mito engine #1035
  - [x] Implement procedure to create table in table-procedure #1040 
  - [x] Integrate procedure manager and create table procedure to datanode #1040
- [x] Procedure for altering a standalone table
  - [x] Implement procedure to alter table on mito engine #1259 
  - [x] Implement procedure to alter table in table-procedure #1354 
- [x] Procedure for dropping a standalone table
  - [x] Implement procedure to drop table on mito engine #1377 
  - [x] Implement procedure to drop table in table-procedure #1401 
- [x] Multi-engine support
  - [x] Procedures for the file table engine #1417 
  - [x] multiple engine procedure management #1434 
- [x] Switch to the procedure framework #1448 
- [x] Metrics #1468
- [x] Remove old DDL implementation #1468
- [x] Remove procedure store path from ProcedureConfig #1489 
- [ ] A unified struct to format lock key
- [x] https://github.com/GreptimeTeam/greptimedb/issues/1727
- [ ] https://github.com/GreptimeTeam/greptimedb/issues/1721
- [ ] #2601

# Other
- Performance
  - Use log-store for state store?
  - We can skip the persistence of some steps to speed up procedures
- More tests

# Reference
- #403 Maybe we can port some codes from this PR if we want to store the execution state to object stores
- #275 The original tracking issue for altering table schema

**Comment by evenyag** [comment]
We also need to change the API of the table engine to use `TableId` to locate the table since if we restart the node while renaming a table, the catalog might still use the old name to open a table.

**Comment by WenyXu** [comment]
Hi, It seems like we need to introduce an asynchronous schema changing pattern (like Google did in F1). It’s attractive to me. Do we have any planning?

**Comment by MichaelScofield** [comment]
It's planned. But I think we should implement distributed procedure framework first. Do you have interesting on that? @WenyXu

**Comment by WenyXu** [comment]
> It's planned. But I think we should implement distributed procedure framework first. Do you have interesting on that? @WenyXu

Cool, let me write an RFC draft

**Comment by evenyag** [comment]
> asynchronous schema changing pattern (like Google did in F1)

A little similar but not the same thing. We don't have transactions and don't plan to provide isolation during schema changing.

To learn more about procedure, please refer to our [RFC](https://github.com/GreptimeTeam/greptimedb/blob/ded31fb069157a6d7c8011e65e0ec18915bc6af9/docs/rfcs/2023-01-03-procedure-framework.md) and [HBase's document](https://github.com/apache/hbase/blob/master/src/main/asciidoc/_chapters/pv2.adoc)

**Comment by evenyag** [comment]
I find out that most procedures need a prepare state, maybe we can add a prepare method to the procedure trait.
