### ISSUE TITLE
Tracking issue for Frontend distribute read/write

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#291]
# create

- [x] create table, "partition by" syntax @MichaelScofield 
- [x] mock Meta, create table and generate partitioning rules @MichaelScofield 
- [ ] Datanode create Region with mock Meta @MichaelScofield 

# insert

in Frontend: @Fengys123 

- [ ] get table schema (region partition info included) from Meta (mock if necessary) and cached locally 
- [ ] execute Grpc insert, split if necessary 
- [ ] integrate with `DistTable` trait 

in Datanode: @waynexia 

- [ ] execute table scan plan via grpc interface

# select

@MichaelScofield 

- [ ] get table schema and parse region keys from sql
- [ ] split and reorganize table scan
- [ ] use formal "remote" catalog manager to manage `DistTable`

[design](https://greptime.feishu.cn/docx/F12ddSJ2foQQ2xxAu7rcZ6XunSb)
[meta](https://greptime.feishu.cn/wiki/wikcnkbbwBZPyveTBN6zeCEXYce)
