### ISSUE TITLE
SQL functions for GreptimeDB administration

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2921]
### What problem does the new feature solve?

We need more functions to query info or do some management jobs in the GreptimeDB. We don't want to add many HTTP APIs for management but just add new SQL functions, because all these functions can be called via `select function_xxx()` through HTTP `/sql` API or MySQL/Postgres protocols.

## Query functions

* [x] `build` function to retrieve the server build info. https://github.com/GreptimeTeam/greptimedb/pull/2919

## Management

* [x] `flush_table` and `flush_region` functions to flush memtables of table or region. https://github.com/GreptimeTeam/greptimedb/pull/3363
* [x] `compact_table` and `compact_region` functions to start a compaction task for table or region. https://github.com/GreptimeTeam/greptimedb/pull/3363
* [x] `migrate_region` to migrate a region from one datanode to another datanode. https://github.com/GreptimeTeam/greptimedb/pull/3325
* [x] `procedure_state` to query procedure state by its id https://github.com/GreptimeTeam/greptimedb/pull/3325

### What does the feature do?

Add functions to query info or do some management jobs in the GreptimeDB

**Comment by sunng87** [comment]
While it's a good idea to use `/sql` instead of dedicated APIs, using functions for these information introduces issues with permission control. 

I have a proposal to put those information behind query functions into `information_schema` tables. So we can take advantages of:

1. Better permission control: Put these tables in `information_schema` of default catalog so we can protect it using catalog read/write permission rules.
2. Query: We can use SQL filters and aggregators on data instead of individual functions for frontend/datanode

No idea for those management functions at the moment. But the final design must include permission control or resource isolation mechanism to prevent them from being called with crossing-tenant effect.

**Comment by killme2008** [comment]
> I have a proposal to put those information behind query functions into information_schema tables.

It's a good idea. We have to provide some scaffold function or structure and demo to help people who are interested in contributing these features.
