### ISSUE TITLE
information_schema improvements

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2931]
### What type of enhancement is this?

API improvement, Configuration, User experience, Other

### What does the enhancement do?

Information Schema provides an ANSI-standard way of viewing system metadata. But we only have two internal tables: `tables` and `columns`, that's not enough for compatibility or such as query functions in #2921 .

Tidb has a great doc that describes its information schema: https://docs.pingcap.com/tidb/stable/information-schema

## Tasks

So I created this tracking issue to add more tables into `information_schema` and welcome all developers who are interested in GreptimeDB to contribute:

* [ ] [CHARACTER_SETS](https://docs.pingcap.com/tidb/stable/information-schema-character-sets), we only supports `utf-8`, so we can just return one row.
* [ ] [CHECK_CONSTRAINTS](https://docs.pingcap.com/tidb/stable/information-schema-check-constraints), we don't support check constrais.
* [ ] [COLLATIONS](https://docs.pingcap.com/tidb/stable/information-schema-collations) and [COLLATION_CHARACTER_SET_APPLICABILITY](https://docs.pingcap.com/tidb/stable/information-schema-collation-character-set-applicability), we don't support them yet
* [ ] `COLUMN_PRIVILEGES`, not implemented.
* [ ] `COLUMN_STATISTICS`, not implemented.
* [ ] [ENGINES](https://docs.pingcap.com/tidb/stable/information-schema-engines), we have `mito`, `file` engines etc.
* [ ] `EVENTS` not implemented.
* [ ] `FILES` not implemented.
* [ ] `GLOBAL_STATUS` not implemented.
* [ ] `GLOBAL_VARIABLES` not implemented. An idea is that we keep all configurations in this table.
* [ ] [KEY_COLUMN_USAGE](https://docs.pingcap.com/tidb/stable/information-schema-key-column-usage), need to implement it.
* [ ] `OPTIMIZER_TRACE` not implemented.
* [ ] `PARAMETERS`  not implemented.
* [ ] [PARTITIONS](https://docs.pingcap.com/tidb/stable/information-schema-partitions), we have the partitions info.
* [ ] `PROFILING` not implemented.
* [ ] `REFERENTIAL_CONSTRAINTS`, we don't support it, returns zero rows instead.
* [ ] `ROUTINES` not implemented.
* [ ] [SCHEMATA](https://docs.pingcap.com/tidb/stable/information-schema-schemata), need to implement it
* [ ] `SCHEMA_PRIVILEGES` not implemented.
* [ ] `SESSION_STATUS` not implemented.
* [ ] [SESSION_VARIABLES](https://docs.pingcap.com/tidb/stable/information-schema-session-variables)
* [ ] [STATISTICS](https://docs.pingcap.com/tidb/stable/information-schema-statistics), we need it
* [ ] `TABLESPACES` not implemented.
* [ ] [TABLE_CONSTRAINTS](https://docs.pingcap.com/tidb/stable/information-schema-table-constraints), we need it
* [ ] `TABLE_PRIVILEGES` not implemented.
* [ ] `TRIGGERS`, we don't support it.
* [ ] [USER_ATTRIBUTES](https://docs.pingcap.com/tidb/stable/information-schema-user-attributes)
* [ ] [USER_PRIVILEGES](https://docs.pingcap.com/tidb/stable/information-schema-user-privileges)
* [ ] [VARIABLES_INFO](https://docs.pingcap.com/tidb/stable/information-schema-variables-info), it's better to have it
* [ ] [VIEWS](https://docs.pingcap.com/tidb/stable/information-schema-views), it can be implemented

All the tables that are not implemented, we can just return zero rows.

Of course, we will have some extension tables:

* [ ] `cluster_info` to provide the current cluster info, such as topology etc.
* [ ] `build_info` to provide the database build info. #2909 
* [ ] `slow_query` to record all slow queries.
* [ ] `table_route` to provide table route info.

## Reference info

1. The `tables` table in information_schema: https://github.com/GreptimeTeam/greptimedb/blob/develop/src/catalog/src/information_schema/tables.rs
2. The `columns` table https://github.com/GreptimeTeam/greptimedb/blob/develop/src/catalog/src/information_schema/columns.rs
3. Add table into `information_schema`:  
https://github.com/GreptimeTeam/greptimedb/blob/99dda93f0ea18ebed7dcf26112d094fcb1c222ea/src/catalog/src/information_schema.rs#L59-L69

**Comment by vivekkoya** [comment]
Hello,

I wish to implement the https://docs.pingcap.com/tidb/stable/information-schema-statistics, Statistics Table. Do you have any pointers or tips regarding besides looking at other table commits?

Thanks
