### ISSUE TITLE
Release blocker of v0.5

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2994]
### What type of enhancement is this?

Other

### What does the enhancement do?

This issue tracks the release progress of `v0.5`.

PRs need to merge:
- [x] https://github.com/GreptimeTeam/greptimedb/pull/2987 @waynexia 
- [x] https://github.com/GreptimeTeam/greptimedb/pull/2971 @niebayes 
- [ ] ~~https://github.com/GreptimeTeam/greptimedb/pull/2993 @niebayes~~
- [ ] ~~https://github.com/GreptimeTeam/greptimedb/pull/2992 @Taylor-lagrange~~
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3000 @waynexia 
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3001 @niebayes 
- [x] https://github.com/GreptimeTeam/greptimedb/pull/2989 @MichaelScofield 
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3008 @waynexia
