### ISSUE TITLE
Tracking Issue: provide official grafana config

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3262]
### What type of enhancement is this?

User experience

### What does the enhancement do?

This issue tracks our official grafana dashboard configurations. It aims to be an intuitive out-of-the-box dashboard for either who wants to hack with GreptimeDB or deploy GreptimeDB.

- Misc.:
  - [x] Export and import grafana setting. And distribute the config with source code https://github.com/GreptimeTeam/greptimedb/pull/3263
- Data:
  - [ ] number of created table in total
  - [ ] storage usage
  - [ ] In/Out bound traffic
- Metrics:
  - [ ] cover all public protocol. Including both HTTP and gRPC (frontend, datanode and metasrv) 
  - [ ] integrate tokio runtime metrics
  - [ ] organize and tag API count and duration by protocol name, not `db` or something else
- Grafana
  - [ ] Adjust version display (smaller area, bigger font size)

**Comment by killme2008** [comment]
I think we can close this issue right now.

Most of them are implemented.
