### ISSUE TITLE
Tracking issue for new region partition rule

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3351]
### What problem does the new feature solve?

Tracks the development progress of RFC #3350

### What does the feature do?

- [x] RFC #3350 
- [x] Change the `PARTITION ON` grammar https://github.com/GreptimeTeam/greptimedb/pull/3347
- [x] Parse the statement to evaluable expr https://github.com/GreptimeTeam/greptimedb/pull/3347
- [x] Implement new partition rule https://github.com/GreptimeTeam/greptimedb/pull/3347
- [x] Add checks to the given rule set
