### ISSUE TITLE
Tracking issue for drop database 

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3516]
### What problem does the new feature solve?

Implement the `Drop database` statement and ensures resources were released correctly
- close #825 
- #3515 

### What does the feature do?

- [x] #3521
- [x] #3534
- [x] #3541
- [x] #3550
- [x] Support to drop metric table #3589
- [x] Invalidate schema name key cache #3695
- [x] Add more tests #3594 
- [x] Add create database procedure (for acquire locks) #3591 
- [ ] Release resources correctly

**Comment by sunng87** [comment]
Please make sure we do not allow cross catalog database drop by default.

**Comment by WenyXu** [comment]
> Please make sure we do not allow cross catalog database drop by default.

Yes, we are under the `catalog` of query context by default.

**Comment by killme2008** [comment]
@WenyXu Looks like we can close this issue.

**Comment by WenyXu** [comment]
Remaining will track in #3515
