### ISSUE TITLE
[Tracking issue] Support database level options and inheritance

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#3708]
### What problem does the new feature solve?

This feature request is a generalization of #1496 which calls for database level TTL.

For tables inside same database, they may share some common configurations, like TTL, compaction strategy, etc. It will be convinient if we can set database options when creating databases and allow all tables in that database inherit these options.

### What does the feature do?

This feature involves 3 subtasks:

- [ ] Allow creating databases with options. Currently `CREATE DATABASE` does not accept any option
- [ ] Read database options when table options is not present during table creation
- [ ] Allow altering table/database options

**Comment by killme2008** [comment]
@v0y4g3r @evenyag Hi, team, I think this task must be prioritized because the database `TTL` really matters in users' scenarios, especially for auto-generated tables.

**Comment by killme2008** [comment]
> @v0y4g3r @evenyag Hi, team, I think this task must be prioritized because the database `TTL` really matters in users' scenarios, especially for auto-generated tables.

I found that database ttl already supported currently:

https://github.com/GreptimeTeam/greptimedb/blob/cc2f7efb983fe057b4efa0cf625d7658a7b5e774/src/operator/src/statement/ddl.rs#L1168

It merge the table options and database options here 👍

**Comment by v0y4g3r** [comment]
> > @v0y4g3r @evenyag Hi, team, I think this task must be prioritized because the database `TTL` really matters in users' scenarios, especially for auto-generated tables.
> 
> I found that database ttl already supported currently:
> 
> https://github.com/GreptimeTeam/greptimedb/blob/cc2f7efb983fe057b4efa0cf625d7658a7b5e774/src/operator/src/statement/ddl.rs#L1168
> 
> It merge the table options and database options here 👍

Yes we now support creating databases with options but still lacks altering database options.
