### ISSUE TITLE
[Tracking issue] open regions in batches

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4026]
### What type of enhancement is this?

Performance, Refactor, Tech debt reduction

### What does the enhancement do?
- [x] #4027 
- [x] Refactor `LogStore`, Add the `WalEntryReader` to decode raw WAL entries into upper-level WAL entries #4038
- [x] Add the `RawEntryReader` to read undecoded raw WAL entries #4030
- [x] #4031
- [x] Open a region in the background #4052 
- [x] Add the `handle_batch_open_requests` to the `RegionEngine` trait and implement the `handle_batch_open_requests` method for the mito engine #4075
- [ ] Add the `handle_batch_open_requests` to the region server  #4107

The whole picture:

![image](https://github.com/GreptimeTeam/greptimedb/assets/32535939/b3849c04-2d00-4bd4-bd5d-fed37d4f5e43)
