### ISSUE TITLE
[Tracking issue] Start flownode as a service

### ISSUE THREAD

**Issue by discord9** [GreptimeTeam/greptimedb#4094]
### What type of enhancement is this?

Feature

### What does the enhancement do?

Run the flownode as a stateless and scalable service, similar to a datanode:

```console
greptime flownode start
```

~~(or maybe `flownode` will be a better naming that is consistent with `datanode`)~~.

### Tasks

The following are the key tasks for implementing the feature. We can still add other related PRs.

1. **Add the control plane between flownode and metasrv** (@discord9 @fengjiachun)
   
   Similar to datanode, the flownode service needs to interact with the metasrv.

   - [x] #4160  @fengjiachun 
   - [x] Register flownode to metasrv; #4164 #4166
   - [x] Send a heartbeat from flownode to metasrv(similar to datanode); @discord9 #4179 

2. **Add the gRPC service for flownode** (@zyy17)

   It may depend on 1.

   - [x] Add the gRPC service for flownode;

4. **Add the subcommand for flownode** (@zyy17)

   It depends on 1 and 2; maybe it can be part of 2.
