### ISSUE TITLE
Tracking Issue: Improve flow functionality

### ISSUE THREAD

**Issue by discord9** [GreptimeTeam/greptimedb#4116]
### What type of enhancement is this?

Other

## v0.9 TODO List
- [x] reuse available scalar function from DataFusion to expand scalar function support
- [x] run in distributed mode with standalone functionality #4094 
- [ ] better arrangement(internal state) design&refactor

## v1.0 TODO List
- [ ] preliminary UDF&UDAF support within flow
- [ ] more time window type, including hop&temporal filter
- [ ] join

**Comment by killme2008** [comment]
@discord9 Let's update this issue status.
