### ISSUE TITLE
[Tracking Issue] Support put directory and compression in Puffin

### ISSUE THREAD

**Issue by zhongzc** [GreptimeTeam/greptimedb#4193]
### What problem does the new feature solve?

In order to support log indexing, we need to let Puffin provide the ability to put directories and compress.

### What does the feature do?

- [x] Support footer lz4 compression
- [x] Introduce puffin manager trait
- [x] Introduce writer for puffin manager
- [x] Introduce cache manager
- [x] Introduce reader for puffin manager
