### ISSUE TITLE
[Tracking issue] Add json datatype

### ISSUE THREAD

**Issue by CookiePieWw** [GreptimeTeam/greptimedb#4230]
### What type of enhancement is this?

Other

### What does the enhancement do?

Support to store and query json data as an independent datatype.

### Tasks

- [x] Build a benchmark to choose the representation of json inside memory and SST files.
   - see https://github.com/CookiePieWw/json-format-in-parquet-benchmark for more information.
- [x] RFC https://github.com/GreptimeTeam/greptimedb/pull/4515
- [x] Add json datatype and other related support.
   - https://github.com/GreptimeTeam/greptimedb/pull/4619
   - Currently the insertions of json type through "PREPARE" and "EXECUTE" stmt are not available.
- [x] Add UDFs for querying json.
   - [x] Add casts between jsonb value and other types, e.g. `parse_jsonb("{\"a\": \"b\"}")`
      - [x] string to json: see `to_json` in #4619 
   - [x] Add functions to query inside json through paths, e.g. `get_by_path_int(".a.b", json)`
      https://github.com/GreptimeTeam/greptimedb/pull/4720
   - [x] Add functions to check if the given json is of specified json type.
      https://github.com/GreptimeTeam/greptimedb/pull/4726

**Comment by WenyXu** [comment]
Future work will be tracked in issue #4805.
