### ISSUE TITLE
Tracking Issue: support full-text index

### ISSUE THREAD

**Issue by zhongzc** [GreptimeTeam/greptimedb#4246]
### What problem does the new feature solve?

Support full-text index.

### What does the feature do?

* [x] Creator for full-text index
* [x] Integrate with sst writer
* [x] CREATE statement support
* [ ] push down `matches` and apply the index

**Comment by killme2008** [comment]
So , there is only one remaining task that integrates the index with the `match` function? @zhongzc

**Comment by zhongzc** [comment]
> So , there is only one remaining task that integrates the index with the `match` function? @zhongzc

Yes, I will send the PR soon.
