### ISSUE TITLE
Redesign backup & restore tool for disaster recovery 

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4276]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

We already have backup & restore tools to backup and restore the database when something goes bad.

But it's not easy to use. You must use the `COPY` SQL and `greptime cli` together.

https://docs.greptime.com/user-guide/administration/disaster-recovery/back-up-&-restore-data

https://docs.greptime.com/user-guide/upgrade#cli

The steps are cumbersome and not user-friendly.

It's better to redesign it for DR, including:

* One tool to get all things done.
* Increment backup both of schema and data.
* Restore from schema and data.

**Comment by fengjiachun** [comment]
### Tasks

- [ ] Export database data in a time range(Incremental Backup) #4382 
- [ ] Import schema and data with cli tool.
- [ ] One tool to get all things done.

**Comment by fengjiachun** [comment]
We now have the [tool](https://docs-version-number.greptime-docs.pages.dev/user-guide/administration/disaster-recovery/back-up-&-restore-data/#export-tool), and it can be closed.
