### ISSUE TITLE
Refactor frontend and datanode functionalities

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#456]
After some discussion, we came to a concensus that all protocol-related logic should be migrated to frontend, including SQL, InfluxDB line protocol, etc. Frontend communicates with datanode thru our gRPC protocol. 

![image](https://user-images.githubusercontent.com/6406592/201521812-857bdcd5-c9a3-4049-9591-e1494b8d73ca.png)

As a result, the "standalone" mode of GreptimeDB should start both frontend and datanode in one process and use inter-process communication like Unix Domain Socket. 
- [x] Move SQL parser logic from datanode to frontend #455
    - [x] CREATE TABLE 
        - CREATE TABLE protocol is already supported in frontend, but we still need to chain the all process together, including table id allocation, table registration and catalog managerment stuff in distributed mode. 
    - [x] CREATE DATABASE
    - [x] SELECT
    - [x] SHOW DATABASES/SHOW TABLES
    - [x] ALTER
       - [x] Add column
       - [x] Drop column #466
- [x] Glue frontend and datanode in one process #471 
  - [x] Current solution creates&starts frontend from datanode as a service, which seems wierd. We should further refactor these logic to `cmd` package, and provide 3 subcommand: `--standalone`/`--frontend`/`--datanode` #455
