### ISSUE TITLE
Tracking issue: Follower region

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4672]
### What problem does the new feature solve?

The current system handles read and write operations on the same datanodes, leading to potential performance bottlenecks under high load. The "follower region" feature separates these operations across different datanodes.

### What does the feature do?

Allows the addition of follower regions to enhance the system's query capabilities. It includes the following improvements:

- [ ] Apply manifest change via remote WAL
- [ ] Replicate leader WAL entries
- [ ] Implement the `SetReplicas` procedure
- [ ] Improve region state transition
- [ ] Implement region-migration related enhancements

**Comment by WenyXu** [comment]
Duplicated with #5739
