### ISSUE TITLE
[Tracking Issue] `RangeReader` as input source of Index

### ISSUE THREAD

**Issue by zhongzc** [GreptimeTeam/greptimedb#4717]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Ref: https://github.com/GreptimeTeam/greptimedb/issues/4594

- [x] `RangeReader` trait
- [x] Adapter from `AsyncRead + AsyncSeek` to `RangeReader`
- [x] Top-down conversion of Input Source of `Index` from `AsyncRead + AsyncSeek` to `RangeReader`
- [x] Implement `RangeReader` for `ObjectStore`
- [x] Instrument `RangeReader`
- [x] Remove the adapter
