### ISSUE TITLE
[Tracking issue] Add more JSON UDFs

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4805]
### What problem does the new feature solve?

The previous tracking issue #4230 introduced some basic JSON UDFs. This tracking issue aims to expand on that by adding more advanced UDFs, enabling more powerful querying capabilities.

### What does the feature do?

- [ ] [JSON_OBJECT_KEYS](https://docs.databend.com/sql/sql-functions/semi-structured-functions/json-object-keys) Returns an Array containing the list of keys in the input JSON Object.
- [ ] [JSON_PATH_EXISTS](https://docs.databend.com/sql/sql-functions/semi-structured-functions/json-path-exists) Checks whether a specified path exists in JSON data.
- [ ] [JSON_PATH_MATCH](https://docs.databend.com/sql/sql-functions/semi-structured-functions/json-path-match) Checks whether a specified JSON path expression matches certain conditions within a JSON data.
...

**Comment by sunng87** [comment]
reference https://www.depesz.com/2024/10/11/sql-json-is-here-kinda-waiting-for-pg-17/

**Comment by qazxcdswe123** [comment]
Hi @WenyXu , I came across this issue and I woner if `JSON_OBJECT_KEYS` is still relavant? (do we still want it in greptimedb?)

The previous attempt https://github.com/GreptimeTeam/greptimedb/pull/5382 was closed because MySQL `Unsupported data type:
    List<String>`, but in #6935 #7096 the datatype get introduced.

I think the issue is still relavant as https://github.com/GreptimeTeam/greptimedb/issues/7685 said we need more json support 😆 

If it's still relavant. I can make a PR on this

**Comment by MichaelScofield** [comment]
@qazxcdswe123 it's still relavant, feel free to make a PR!

**Comment by qazxcdswe123** [comment]
Hi @MichaelScofield, when working on this, I found a potential performance improvement。

For now we are forced to read and process the entire jsonb input (i.e: `parse_jsonb` that materialize both key and value), but databends' approach use `RawJsonb::object_keys()`, which only reads in keys, and this could be 9x perf diff from my benchmark, but it's added in a later version of `jsonb`

| Scenario | Time (full) | Time (key only) | Slowdown |
|---|---|---|---|
| 10 keys | ~2134 ns | ~294 ns | ~7.3× |
| 100 keys | ~23313 ns | ~2640 ns | ~8.8× |
| 100 keys + deeply nested object | ~351251 ns | ~39151 ns | ~9× |

Here are 3 possible approaches.

1. Use handwritten jsonb parser, write directly to Arrow builder, we can add an additional malformed data check, but hard to maintain and review in the long term.
2. Use `RawJsonb::object_keys()` as databend, but need to update `jsonb` lib version first, and this need to be done in a seperate PR.
3. Accept the slow solution for now and leave a todo in the comment to address it later (and probably will never come back xD) .

What do you think?

**Comment by MichaelScofield** [comment]
@qazxcdswe123 I vaguely remember there're some compatibility problems in upgrading the jsonb dependency. Can you verify that? If there weren't or can be easily fixed, we are happily accept upgrading it.
