### ISSUE TITLE
Support drop table clause

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#497]
This ticket tracks the process of supporting `DROP TABLE` caluse.

Tasks:
- [x] add `deregister_table()` and implement it for `MemoryCatalogManager` #620 
- [x] `DROP TABLE` in standalone mode
  - [x] using `MemoryCatalogManager` #630
  - [x] using local catalog #913
- [x] `DROP TABLE` in distributed mode #944 
- [x] `drop route` in meta service #707 
- [ ] Background resource GC task #1556

**Comment by evenyag** [comment]
#801 is merged, we could implement DROP TABLE on the local catalog now.
