### ISSUE TITLE
Implement leader election over postgresql

### ISSUE THREAD

**Issue by CookiePieWw** [GreptimeTeam/greptimedb#5208]
### What type of enhancement is this?

Other

### What does the enhancement do?

- [x] Candidate registration 
   - [x] Init #5209 
   - [x] Separate registration and keep alive logics #5320 
- [x] Leader election #5249 
- [x] Txn
   - [x] Connection Pool #5260 
   - [x] Txn Impl #5266
- [x] Config
   - [x] Configurable pg kv backend table name #5244
   - [x] Configurable advisory lock id #5244
   - [x] ~~Configurable isolation level for txn~~ Only serializable can be set.
- [ ] Tests
  - [x] Unit test for Txn
     - [x] Init #5266
     - [x] Fix concurrent problem when multiple unit test are executed
            ~~Hopefully we can~~ get it done in #5266 too.
  - [x] Sqlness #5309 
  - [ ] Integration

**Comment by killme2008** [comment]
Let's close this issue. Thanks a lot.
