### ISSUE TITLE
Supports PromQL natively

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#596]
### What problem does the new feature solve?

Right now GreptimeDB only supports [SQL and gRPC](https://docs.greptime.com/user-guide/reading-writing-data) protocols to query data.
[PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/) prevails in cloud-native observability. We want to support PromQL natively in GreptimeDB, so I open this issue to track it.

* [x] [Design draft](https://github.com/GreptimeTeam/greptimedb/issues/596#issuecomment-1340600220) and [RFC](https://github.com/GreptimeTeam/greptimedb/pull/779)
* [x] PoC https://github.com/waynexia/corroding-prometheus

### What does the feature do?

Supports PromQL natively.

### Implementation challenges

There are some challenges to supporting PromQL in GreptimeDB:
* The data mode between Prometheus and greptimedb doesn't match totally. There is a conversion between them.
* The PromQL has an interpreter to compute data and has a lot of [functions](https://prometheus.io/docs/prometheus/latest/querying/functions/).
* PromQL has lots of special data processing logic for metrics scenarios.
* The performance challenge. We don't just only support PromQL, but also want to provide better performance by pushing down predicate/aggregation etc.
* How to catch up community's progress. We don't want a forked language.

### Procedure

- [x] Parser (in https://github.com/GreptimeTeam/promql-parser) @yuanbohan 
- [x] Basic Plans
  - [x] SeriesNormalize #787
  - [x] MatrixManipulator
    - [x] Range Array #796
    - [x] Manipulator #843 
  - [x] VectorManipulator #803
- [ ] Try unary, binary and aggregator provided by DataFusion
  - [x] Binary Expr Planner #889 
  - [x] Aggregator Planner #870
  - [ ] Unary Expr Planner
  - [ ] Literal-only binary expr
- [ ] Planner
  - [x] Skeleton #828
  - [x] Instant Selector, Instant Function #828
  - [x] `group by` & `group without` #870 
  - [ ] Range Vector
    - [x] Range Selector #870
    - [x] Function `increase`/`idelta`/`irate` #880
    - [ ] Other range functions
  - [ ] Paren Expr and Subquery Expr
- [x] HTTP Interface #924
- [x] HTTP codec #1022
- [ ] Transplant other PromQL operators

### Compliance Test

https://github.com/prometheus/compliance/tree/main/promql

The follow-up works are tracked at https://github.com/GreptimeTeam/greptimedb/issues/1042

**Comment by SSebo** [comment]
https://github.com/vthriller/promql this crate may be useful, but seems out dated.

**Comment by killme2008** [comment]
## Motivation
The [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/) supported by Prometheus is used widely in cloud-native observability.  We want to enable it natively in the GreptimeDB. 
The GreptimeDB already supports [remote read/write protocol for Prometheus](https://docs.greptime.com/user-guide/supported-protocols/prometheus). But it's not good enough for performance and DevOps. We want to implement PromQL in pure Rust, and cooperate reasonably with our query engine and table engine. We want to push computation down  into storage, reducing data transfer and providing the best performance. And also keep compatible with  Prometheus.
## Design(draft)

The PromQL in Prometheus:
![image](https://user-images.githubusercontent.com/14142/206131597-86ef720b-eb01-4a14-a141-b19cb7924d59.png)

Including:
- Parser:  parse the PromQL string into AST. Refer to the source code [parser](https://github.com/prometheus/prometheus/tree/main/promql/parser).
- Engine: contains an [evaluator](https://github.com/prometheus/prometheus/blob/main/promql/engine.go) to eval the AST, querying data from storage and call [functions](https://github.com/prometheus/prometheus/blob/main/promql/functions.go).
- Storage: time series [storage](https://github.com/prometheus/prometheus/blob/main/storage/interface.go), providing data to the engine.
So our design will focus on these three parts too.
 
### Parser
Looks like Prometheus is using yacc to generate the parser. I think we can use it too. Hand-wiring is another choice, but I think it's not necessary. Using the same [grammar file](https://github.com/prometheus/prometheus/blob/main/promql/parser/generated_parser.y) is a better way to make our parser compatible with Prometheus easily.

### Engine(Evaluator)
The evaluator  is the core part of the engine:
```go
// An evaluator evaluates given expressions over given fixed timestamps. It
// is attached to an engine through which it connects to a querier and reports
// errors. On timeout or cancellation of its context it terminates.
type evaluator struct {
        ctx context.Context

        startTimestamp int64 // Start time in milliseconds.
        endTimestamp   int64 // End time in milliseconds.
        interval       int64 // Interval in milliseconds.

        maxSamples               int
        currentSamples           int
        logger                   log.Logger
        lookbackDelta            time.Duration
        samplesStats             *stats.QuerySamples
        noStepSubqueryIntervalFn func(rangeMillis int64) int64
}
```

The core function is eval:
```go
// eval evaluates the given expression as the given AST expression node requires.
func (ev *evaluator) eval(expr parser.Expr) (parser.Value, storage.Warnings) {
    ....
 }
```

It would be the most complex part of our work.

There are 70 functions at[ functions.go](https://github.com/prometheus/prometheus/blob/main/promql/functions.go).  They can be implemented step by step.

### Storage

TODO

### Test
Prometheus provides a compatible test suite for other implementations. https://github.com/promlabs/promql-compliance-tester
We can use it to test our implementation.

## Milestones

The first milestone may be in 2022, January. Make the PromQL run and let the compatible test cases pass over 60%.

**Comment by waynexia** [comment]
Follow-up works are tracked at https://github.com/GreptimeTeam/greptimedb/issues/1042
