### ISSUE TITLE
GreptimeDB Roadmap 2023

### ISSUE THREAD

**Issue by xtang** [GreptimeTeam/greptimedb#669]
## Overview
GreptimeDB set off in April 2022 and had just open-sourced on Nov. 15th, 2022. Many of our ideas are still on their way, yet to be polished. As we work towards GreptimeDB 2023, it's natural to ask what's next. This roadmap presents goals our team is working on and concepts we have for our shared community.

- To give people a sense of what to expect in GreptimeDB over the next 6 months;
- for those who would like to contribute to GreptimeDB, to help provide "starting points" for how to get involved, and a sense of what kind of projects we are looking for.

We will focus on three main sections:

- Distributed solution at the production level 
- Deeply optimize storage and query engine 
- Compatible with open protocols

Everyone can easily find all the issues&PRs related to this Roadmap [here](https://github.com/GreptimeTeam/greptimedb/milestone/2)

#### Features
- [ ] Incorporate Quorum-based WAL (as an independent subproject): #626
- [x] Analyze Query: #608 
- [ ] Design observability system tables: #602 
- [x] Enable MySQL/PostgreSQL TLS (suit for new contributors): #515
- [x] Improve fault tolerance using distributed DDL framework #286 
- [x] Integration tests #487 
#### Refactor
- [x] Reconstruct gRPC, the data transmission protocol 
#### Features
- [x] Add user-defined window functions #103 
- [x] Escalate compaction L0 up to L1, & involve TTL #601
- [x] Allow multi-region in engine #625
- [x] Enable object storage, for example, S3 #652 
- [ ] Continuous aggregating and downsampling #638
#### Refactor
- [x] Refact DataFusion & Arrow related components #555 
- [ ] Incorporate time series index 
#### Performance
- [x] Optimize memtable
- [x] Improve distributed queries 
- [ ] Add SST's filter & index 
- [ ] Optimize python coprocessor 
#### Features
- [x] Enable PromQL (suit for new contributors) #596 
- [x] Permit PreparedStatement  (suit for new contributors) #470 
- [x] Be capable of Session (suit for new contributors) #600 
- [x] Provide SDK of multi-language (suit for new contributors) 
   - [x] #606
   - [x] #607
   
## How you can help
If anything above draws your attention, don't hesitate to join us on [GitHub Discussion](https://github.com/GreptimeTeam/greptimedb/discussions), or Join [GreptimeDB Community on Slack](https://join.slack.com/t/greptimedbcommunity/shared_invite/zt-1jeggrthh-UDISaSqdYUZTtf8wbGxgFg) if you have doubts and would like to talk about it first.

Looking beyond the initiatives that are in progress, there's a lot of room for improvement. Here are some other ideas we'd like to see. For many of these ideas, the main thing they need is someone to own the design! If you might be interested in giving that a try, speak up and chat with the team. We probably will end up being the ones who get you the best.

**Comment by tisonkun** [comment]
Most actions are finished. Welcome to join the Roadmap 2024 at https://github.com/GreptimeTeam/greptimedb/issues/3412.
