### ISSUE TITLE
supports "use" stmt in mysql

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#670]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Support "use" stmt in mysql. It's required when clients use jdbc.

### Implementation challenges

- [x] Implement a bare sketch of session, and support "use" in mysql server
- [x] Modify insertion and selection related codes in Datanode
- [x] Modify other sql related codes in Datanode
- [x] Support "use" in Frontend
