### ISSUE TITLE
Tracking Issue: Supports rename table 

### ISSUE THREAD

**Issue by e1ijah1** [GreptimeTeam/greptimedb#723]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

As discussed in #660 , we decide to using table id as the table data path  to support `RENAME TABLE`. This issue tracks the progress of this work.

### Implementation challenges

This feature will be implemented in the following steps:
- [x] change the table path to schema/table_id #728 
- [x] support renaming tables in the mito table engine, this may require to #802 
  - persist the change to manifest (maybe a new MetaAction is required)
  - change the in-memory metadata
  - recover the change when reopening the table
- [x] support renaming tables for the catalog manager in standalone mode #824 
  - update the catalog's metadata
- [ ] support rename table in distribute mode
- [x] support parsing the RENAME TABLE statements in the parser and execute the rename statement #780

**Comment by killme2008** [comment]
Looks like we already implement it. Thanks a lot @e1ijah1

**Comment by evenyag** [comment]
@killme2008 rename is not implemented in cluster mode, we might need to reopen this.
