### ISSUE TITLE
Tracking issue for delete

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#755]
### What problem does the new feature solve?

This is a tracking issue for implementing delete for greptiimedb, also solves #614 

### What does the feature do?

The final goal is to support the `DELETE` SQL statement, but we may provide a minimal usable version first, which only allows deleting by primary key, or even only exposes the `delete()` method in the table interface.

### Implementation challenges

The steps to implement a minimal version that supports deletion are
- [x] Support deleting by key in the storage engine #614 #777
- [x] Support deleting by primary key in the mito table #801
- [x] Support the `DELETE` SQL statement but require specifying the full primary key (and the timestamp)
- [ ] Support deletion in distributed mode
- [x] Support `DELETE` with general "where" condition #1222

#### Related Issues
- [x] Delete rows in table with non-null value column #848

**Comment by evenyag** [comment]
I have created the PR #775 to do the `WriteBatch` refactoring. I plan to experiment with the delete API in another PR.

**Comment by jun0315** [comment]
@evenyag  Hi, I see on greptimeDB WeChat official account that we do not support delete SQL at present. If possible, I want to try this part:D

**Comment by evenyag** [comment]
> Hi, I see on greptimeDB WeChat official account that we do not support delete SQL at present. If possible, I want to try this part:D

@jun0315  Sure! You could try this task.
>  Support the `DELETE` SQL statement but require specifying the full primary key (and the timestamp)

The sqlparser-rs crate supports [delete statement](https://docs.rs/sqlparser/latest/sqlparser/ast/enum.Statement.html#variant.Delete) so we could just use it.

But the table trait requires providing all key columns in order to form the key and delete that key in the underlying storage engine. So we might only implement the simplest delete statement that: only uses `=`, `and` in the where clause and provides all columns needed by the key.
```sql
delete from my_table where k1 = xxx and k2 = xxx and timestamp = xxx;
```

A better approach might be invoking the query engine to scan all the keys and then delete them, so we could support more complex where clauses.

**Comment by waynexia** [comment]
> If k1 is not specified, do we throw an exception or automatically ignore the filter condition of k1

Ignoring unspecified columns is fine. Other common DBMSs also act like this.

**Comment by jun0315** [comment]
> Ignoring unspecified columns is fine. Other common DBMSs also act like this.

Ok, thank you. I have identified the requirements:D

**Comment by evenyag** [comment]
> If k1 is not specified, do we throw an exception or automatically ignore the filter condition of k1

You could ignore them in the SQL layer. The underlying table implementation checks whether all key columns are provided and returns error if there are missing columns.
