### ISSUE TITLE
Add `close` method for `Region` trait

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#832]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

A `close` method  should be added to `Region` trait so that the resources held by `Region` can be gracefully release, for example, when a table is dropped.

### Implementation challenges

In order to gracefully close a region, we need to implement following tasks:
- [ ] flag the region as "closed" to prevent future writes #970;
    - In distributed mode, region state should be maintained in metasrv and regions should be agnostic to state implementations. But we can start from maintaing the state in datanode's memory;
- [ ] regions spawn background tasks to handle table flush or compaction etc, these tasks need to be cancelled #970.
    - [ ] Flush task handle
https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/storage/src/region/writer.rs#L513
    - [ ] Compaction task handle is not present until #930 is resolved.

**Comment by evenyag** [comment]
We could acquire the write lock of the region (so we can ensure all pending writes before close are done) and mark the region as closing

**Comment by WenyXu** [comment]
Cool, can I take this

**Comment by WenyXu** [comment]
I'm currently work on the part that shut down the server gracefully when it received the ctrl-c signal (and I guess we also need to handle the SIGTERM), But I encountered some issues. The `Command` didn't return a server instance, so I need to design a pattern to notify the instance held by `Command`. 

https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/cmd/src/bin/greptime.rs#L33-L37

The first pattern that came to my mind is to use a channel and pass the channel as a part of ctx into `Command`'s `run` method. It will look like the following:

```rust
  let (rx, tx) = channel();

    let ctx = Context { sigterm: tx };

    tokio::select! {
        result = cmd.run(ctx) => {
            if let Err(err) = result {
                error!(err; "Fatal error occurs!");
            }
        }
        _ = tokio::signal::ctrl_c() => {
            info!("Goodbye!");
            rx.send(());
        }
    }
```

Then we can handle the signal in the `StartCommand`'s `run` method.

https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/cmd/src/datanode.rs#L68-L83

Is this a good solution? Any suggestions are welcomed.

**Comment by evenyag** [comment]
Could we add another enum, like `Application` to wrap structs like `Datanode`, `Frontend`?
```rust
enum Application {
    Datanode(Datanode),
    Frontend(Frontend),
}
```

We build the application from the command and run that application.
```rust
let app = cmd.build();
tokio::select! {
    result = app.run(ctx) => {},
    _ = tokio::signal::ctrl_c() => {
        app.stop();
    }
}
```

**Comment by evenyag** [comment]
@v0y4g3r Maybe we could change this into a tracking issue to graceful shutdown
