### ISSUE TITLE
Support table compaction

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#930]
### What type of enhancement is this?

Performance

### What does the enhancement do?

So far GreptimeDB supports flushing rows in memtable to SST files in level 0. But SST files in level 0 is not sorted in time bucket order, so retrieving rows in a given time range needs to scan all SST files in level 0. Just like other LSM tree based storage engines, we need to compact SST files in different levels to:
- merge insert/delete records with the same primary key;
- sort all rows in timestamp order and evenly distribute those rows to SST files in level 1 so that no SST file in level 1 contains intersecting time range;
- delete expired SST files according to TTL;
- we can intriduce compression and indexing tasks when compacting SST files in the future.

![image](https://user-images.githubusercontent.com/6406592/216251395-beb1c2ed-155f-488d-94e5-c518b9121d3f.png)

The RFC can be found at #939.

### Implementation challenges

We need to implement those component:
- [x] compaction scheduler (along with task control to limit performance impact to foreground queries) #947;
- [x] compaction strategy: we can begin with file-num based strategy that trigger compaction as soon as the number of SST files in level 0 exceeds some threshold #964;
    - [x] time bucket calculation: read time ranges of SST files in level 0 and calculate the proper time bucket for level 1 SST files so that data can be evenly distributed in level 1 SST files;
track the referencer of SST files and only delete these SSTs when it's been marked as "deleted" and reference count is 0.
- [x] table compaction task: use merged reader along with dedup reader to read rows from all SST files in level 0 #972.
- [x] integrate compaction components to datanode instance #997.

### Future work
- [ ] We may break the snapshot read semantic when implementing compaction, since with the same sequence for snapshot read, the seceond read may find some rows are deleted because of compaction.
- [x] Persist time window config into region manifest to ensure Level1's time window size remains consistent. #1055
- [x] Refactor region SST struct to hold an UUID as SST key to reduce overhead. #1053
- [x] purge SST files to reclaim disk space #601 ;
    - [x] purge compacted SST files #1030;
    - [x] purge expired SST files according to table TTL
        - [x] issue #601 
        - [x] pull request #1052
- [ ] Support more compaction strategies
    - [x] #1068

**Comment by killme2008** [comment]
>  we may break the snapshot read semantic when implementing compaction, since with the same sequence for snapshot read, the second read may find some rows are deleted because of compaction.

Do we have any solutions to fix this issue? Looks like it's impossible.

**Comment by waynexia** [comment]
>Do we have any solutions to fix this issue? Looks like it's impossible.

Maybe we need to introduce some mechanism like MVCC for it, but I think it's not necessary to do so.

**Comment by evenyag** [comment]
> we may break the snapshot read semantic when implementing compaction, since with the same sequence for snapshot read, the second read may find some rows are deleted because of compaction.

I think this might not be a problem. Now we only support reading the latest data. In this case, we acquire a reference to a stable `Version` struct which references the old SSTs. But we need to make the file metadata reference counted and delete the file after no "read" referencing it.

> Do we have any solutions to fix this issue?

Introduces snapshot like other [dbs](https://github.com/google/leveldb/blob/fb644cb44539925a7f444b1b0314f402a456c5f4/include/leveldb/db.h#L102) if we need a stable snapshot but also want to release the unused SSTs.

**Comment by killme2008** [comment]
I think we can close this issue. Open a new issue when we want to support other compaction features.
