### ISSUE TITLE
Support to invoke PromQL via SQL interface

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#986]
### What problem does the new feature solve?

Be able to invoke PromQL in current SQL interfaces, like PG/MySQL.

### What does the feature do?

The proposed grammar:

```sql
PQL EVAL (start, end, step) <promql>

PQL EXPLAIN|ANALYZE <promql>
```

### Tasks:

- [x] Implement `TQL EVAL` clause #1047
- [x] Implement `TQL EXPLAIN` clause #1427 
- [x] Implement `TQL ANALYZE` clause
- [x] Implements `TQL` in cluster version

**Comment by waynexia** [comment]
It can be optional if we could figure out a reasonable default value.

**Comment by killme2008** [comment]
Our extension to PromQL including:

* Translate the expression into the query plan and execute it by the query engine.
* Supports multi-value fields
* Custom functions (by Python)

In the future, we want to enable it to query trace and log. As discussed, we can call our extension to be **Telemetry QL**: a query language to query telemetry data.

So the grammar changed to:

```
TQL eval (start, end, step) <expr>
TQL explain <expr>
```

**Comment by etolbakov** [comment]
hey @waynexia 
I would like to give it a go

**Comment by waynexia** [comment]
Thanks, I'll add more detail later
